server:
  port: 58082
spring:
  main:
    allow-bean-definition-overriding: true
  application:
    name: study-kubernetes # 应用名称
  datasource:
    driverClassName: com.mysql.cj.jdbc.Driver
    name: study-kubernets-db
    url: jdbc:mysql://localhost:3306/kubernetes?rewriteBatchedStatements=true&characterEncoding=utf8&useUnicode=true&useSSL=false&allowPublicKeyRetrieval=true&serverTimezone=Asia/Shanghai
    username: root
    password: Admin_409012
mybatisPlus:
  configuration:
    logImpl: org.apache.ibatis.logging.stdout.StdOutImpl
